# Generated by Django 4.0 on 2021-12-29 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='users.user'),
        ),
        migrations.AddField(
            model_name='retweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retweet', to='tweet.tweet'),
        ),
        migrations.AddField(
            model_name='media',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tweet.tweet'),
        ),
        migrations.AddField(
            model_name='like',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='tweet.tweet'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='users.user'),
        ),
        migrations.AddField(
            model_name='quotetweet',
            name='quoted_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_tweet', to='tweet.quotetweet'),
        ),
    ]
