# Generated by Django 3.2.10 on 2022-01-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.IntegerField(max_length=5, verbose_name=[(1, '星1'), (2, '星2'), (3, '星3'), (4, '星4'), (5, '星5')]),
        ),
    ]
