# Generated by Django 3.2.10 on 2022-01-04 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_like_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotetweet',
            name='quoted_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_tweet', to='tweet.tweet'),
        ),
    ]
