# Generated by Django 3.2.10 on 2022-01-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_quotetweet_quoted_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotetweet',
            name='quote_message',
        ),
    ]
