# Generated by Django 4.0 on 2021-12-29 06:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('username', models.CharField(error_messages={'unique': 'このユーザ名はすでに使用されています'}, help_text="ユーザー名は4~30文字の英数字と'_'が使用できます", max_length=30, unique=True, validators=[users.models.UsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='Username')),
                ('display_name', models.CharField(max_length=50, verbose_name='表示名')),
                ('bio', models.TextField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to=users.models.user_icon_path)),
                ('header', models.FileField(blank=True, null=True, upload_to=users.models.user_header_path)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Emailアドレス')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='アカウント作成日')),
                ('is_staff', models.BooleanField(default=False, help_text='管理サイトにログインできるかを指定します。', verbose_name='スタッフ権限')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_date', models.DateTimeField(auto_now_add=True)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.user')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='users.user')),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(related_name='followers', through='users.Friends', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
