# Generated by Django 3.2.10 on 2021-12-29 08:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='', max_length=50, verbose_name='表示名'),
        ),
    ]
